/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentStudyPlanRouteImport } from './routes/student.study-plan'
import { Route as StudentResourcesRouteImport } from './routes/student.resources'
import { Route as StudentQuizRouteImport } from './routes/student.quiz'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentFlashcardsRouteImport } from './routes/student.flashcards'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminLecturesRouteImport } from './routes/admin.lectures'
import { Route as StudentSubjectsIndexRouteImport } from './routes/student.subjects.index'
import { Route as StudentQuizIndexRouteImport } from './routes/student.quiz.index'
import { Route as StudentFlashcardsIndexRouteImport } from './routes/student.flashcards.index'
import { Route as StudentSubjectsIdRouteImport } from './routes/student.subjects.$id'
import { Route as StudentQuizTopicIdRouteImport } from './routes/student.quiz.$topicId'
import { Route as StudentNotesTopicIdRouteImport } from './routes/student.notes.$topicId'
import { Route as StudentFlashcardsTopicIdRouteImport } from './routes/student.flashcards.$topicId'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentStudyPlanRoute = StudentStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResourcesRoute = StudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizRoute = StudentQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFlashcardsRoute = StudentFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => StudentRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLecturesRoute = AdminLecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => AdminRoute,
} as any)
const StudentSubjectsIndexRoute = StudentSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizIndexRoute = StudentQuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentQuizRoute,
} as any)
const StudentFlashcardsIndexRoute = StudentFlashcardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentFlashcardsRoute,
} as any)
const StudentSubjectsIdRoute = StudentSubjectsIdRouteImport.update({
  id: '/subjects/$id',
  path: '/subjects/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizTopicIdRoute = StudentQuizTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => StudentQuizRoute,
} as any)
const StudentNotesTopicIdRoute = StudentNotesTopicIdRouteImport.update({
  id: '/notes/$topicId',
  path: '/notes/$topicId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFlashcardsTopicIdRoute =
  StudentFlashcardsTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => StudentFlashcardsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/lectures': typeof AdminLecturesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/login': typeof AdminLoginRoute
  '/student/flashcards': typeof StudentFlashcardsRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/student/quiz': typeof StudentQuizRouteWithChildren
  '/student/resources': typeof StudentResourcesRoute
  '/student/study-plan': typeof StudentStudyPlanRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/flashcards/$topicId': typeof StudentFlashcardsTopicIdRoute
  '/student/notes/$topicId': typeof StudentNotesTopicIdRoute
  '/student/quiz/$topicId': typeof StudentQuizTopicIdRoute
  '/student/subjects/$id': typeof StudentSubjectsIdRoute
  '/student/flashcards/': typeof StudentFlashcardsIndexRoute
  '/student/quiz/': typeof StudentQuizIndexRoute
  '/student/subjects/': typeof StudentSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/lectures': typeof AdminLecturesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/login': typeof AdminLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRoute
  '/student/study-plan': typeof StudentStudyPlanRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/flashcards/$topicId': typeof StudentFlashcardsTopicIdRoute
  '/student/notes/$topicId': typeof StudentNotesTopicIdRoute
  '/student/quiz/$topicId': typeof StudentQuizTopicIdRoute
  '/student/subjects/$id': typeof StudentSubjectsIdRoute
  '/student/flashcards': typeof StudentFlashcardsIndexRoute
  '/student/quiz': typeof StudentQuizIndexRoute
  '/student/subjects': typeof StudentSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/lectures': typeof AdminLecturesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/student/flashcards': typeof StudentFlashcardsRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/student/quiz': typeof StudentQuizRouteWithChildren
  '/student/resources': typeof StudentResourcesRoute
  '/student/study-plan': typeof StudentStudyPlanRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/flashcards/$topicId': typeof StudentFlashcardsTopicIdRoute
  '/student/notes/$topicId': typeof StudentNotesTopicIdRoute
  '/student/quiz/$topicId': typeof StudentQuizTopicIdRoute
  '/student/subjects/$id': typeof StudentSubjectsIdRoute
  '/student/flashcards/': typeof StudentFlashcardsIndexRoute
  '/student/quiz/': typeof StudentQuizIndexRoute
  '/student/subjects/': typeof StudentSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/student'
    | '/admin/lectures'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/login'
    | '/student/flashcards'
    | '/student/profile'
    | '/student/quiz'
    | '/student/resources'
    | '/student/study-plan'
    | '/admin/'
    | '/student/'
    | '/student/flashcards/$topicId'
    | '/student/notes/$topicId'
    | '/student/quiz/$topicId'
    | '/student/subjects/$id'
    | '/student/flashcards/'
    | '/student/quiz/'
    | '/student/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/lectures'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/login'
    | '/student/profile'
    | '/student/resources'
    | '/student/study-plan'
    | '/admin'
    | '/student'
    | '/student/flashcards/$topicId'
    | '/student/notes/$topicId'
    | '/student/quiz/$topicId'
    | '/student/subjects/$id'
    | '/student/flashcards'
    | '/student/quiz'
    | '/student/subjects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/student'
    | '/admin/lectures'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin_/login'
    | '/student/flashcards'
    | '/student/profile'
    | '/student/quiz'
    | '/student/resources'
    | '/student/study-plan'
    | '/admin/'
    | '/student/'
    | '/student/flashcards/$topicId'
    | '/student/notes/$topicId'
    | '/student/quiz/$topicId'
    | '/student/subjects/$id'
    | '/student/flashcards/'
    | '/student/quiz/'
    | '/student/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/study-plan': {
      id: '/student/study-plan'
      path: '/study-plan'
      fullPath: '/student/study-plan'
      preLoaderRoute: typeof StudentStudyPlanRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/resources': {
      id: '/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof StudentResourcesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz': {
      id: '/student/quiz'
      path: '/quiz'
      fullPath: '/student/quiz'
      preLoaderRoute: typeof StudentQuizRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/flashcards': {
      id: '/student/flashcards'
      path: '/flashcards'
      fullPath: '/student/flashcards'
      preLoaderRoute: typeof StudentFlashcardsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lectures': {
      id: '/admin/lectures'
      path: '/lectures'
      fullPath: '/admin/lectures'
      preLoaderRoute: typeof AdminLecturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/subjects/': {
      id: '/student/subjects/'
      path: '/subjects'
      fullPath: '/student/subjects/'
      preLoaderRoute: typeof StudentSubjectsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz/': {
      id: '/student/quiz/'
      path: '/'
      fullPath: '/student/quiz/'
      preLoaderRoute: typeof StudentQuizIndexRouteImport
      parentRoute: typeof StudentQuizRoute
    }
    '/student/flashcards/': {
      id: '/student/flashcards/'
      path: '/'
      fullPath: '/student/flashcards/'
      preLoaderRoute: typeof StudentFlashcardsIndexRouteImport
      parentRoute: typeof StudentFlashcardsRoute
    }
    '/student/subjects/$id': {
      id: '/student/subjects/$id'
      path: '/subjects/$id'
      fullPath: '/student/subjects/$id'
      preLoaderRoute: typeof StudentSubjectsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz/$topicId': {
      id: '/student/quiz/$topicId'
      path: '/$topicId'
      fullPath: '/student/quiz/$topicId'
      preLoaderRoute: typeof StudentQuizTopicIdRouteImport
      parentRoute: typeof StudentQuizRoute
    }
    '/student/notes/$topicId': {
      id: '/student/notes/$topicId'
      path: '/notes/$topicId'
      fullPath: '/student/notes/$topicId'
      preLoaderRoute: typeof StudentNotesTopicIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/flashcards/$topicId': {
      id: '/student/flashcards/$topicId'
      path: '/$topicId'
      fullPath: '/student/flashcards/$topicId'
      preLoaderRoute: typeof StudentFlashcardsTopicIdRouteImport
      parentRoute: typeof StudentFlashcardsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLecturesRoute: typeof AdminLecturesRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLecturesRoute: AdminLecturesRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentFlashcardsRouteChildren {
  StudentFlashcardsTopicIdRoute: typeof StudentFlashcardsTopicIdRoute
  StudentFlashcardsIndexRoute: typeof StudentFlashcardsIndexRoute
}

const StudentFlashcardsRouteChildren: StudentFlashcardsRouteChildren = {
  StudentFlashcardsTopicIdRoute: StudentFlashcardsTopicIdRoute,
  StudentFlashcardsIndexRoute: StudentFlashcardsIndexRoute,
}

const StudentFlashcardsRouteWithChildren =
  StudentFlashcardsRoute._addFileChildren(StudentFlashcardsRouteChildren)

interface StudentQuizRouteChildren {
  StudentQuizTopicIdRoute: typeof StudentQuizTopicIdRoute
  StudentQuizIndexRoute: typeof StudentQuizIndexRoute
}

const StudentQuizRouteChildren: StudentQuizRouteChildren = {
  StudentQuizTopicIdRoute: StudentQuizTopicIdRoute,
  StudentQuizIndexRoute: StudentQuizIndexRoute,
}

const StudentQuizRouteWithChildren = StudentQuizRoute._addFileChildren(
  StudentQuizRouteChildren,
)

interface StudentRouteChildren {
  StudentFlashcardsRoute: typeof StudentFlashcardsRouteWithChildren
  StudentProfileRoute: typeof StudentProfileRoute
  StudentQuizRoute: typeof StudentQuizRouteWithChildren
  StudentResourcesRoute: typeof StudentResourcesRoute
  StudentStudyPlanRoute: typeof StudentStudyPlanRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentNotesTopicIdRoute: typeof StudentNotesTopicIdRoute
  StudentSubjectsIdRoute: typeof StudentSubjectsIdRoute
  StudentSubjectsIndexRoute: typeof StudentSubjectsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentFlashcardsRoute: StudentFlashcardsRouteWithChildren,
  StudentProfileRoute: StudentProfileRoute,
  StudentQuizRoute: StudentQuizRouteWithChildren,
  StudentResourcesRoute: StudentResourcesRoute,
  StudentStudyPlanRoute: StudentStudyPlanRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentNotesTopicIdRoute: StudentNotesTopicIdRoute,
  StudentSubjectsIdRoute: StudentSubjectsIdRoute,
  StudentSubjectsIndexRoute: StudentSubjectsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
