// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkhdmsggbohlvbnaokuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraGRtc2dnYm9obHZibmFva3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5MjQ3NTMsImV4cCI6MjA5OTUwMDc1M30.-8-QfWMmddlVd8-_sDjjZJuhepA7tnolyEhecrJPoqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});